name: Install Bit CLI
description: Installs the Bit CLI to be used by any action
inputs:
  bit_token:
    description: 'The bit auth token'
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install Bit Version Manager
      run: npm i -g @teambit/bvm
      shell: bash
    - name: Install latest Bit version
      run: bvm install
      shell: bash
    - name: add bvm bin folder to path
      run: echo "$HOME/bin" >> $GITHUB_PATH
      shell: bash
    - name: Set up bit config
      run: |
        bit config set analytics_reporting false
        bit config set anonymous_reporting false
        bit config set user.token ${{ inputs.bit_token }}
      shell: bash
